# Generated by Django 4.1.3 on 2022-12-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminarioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('fecha', models.DateField()),
                ('institucion', models.CharField(max_length=50)),
                ('hora', models.TimeField()),
                ('estado', models.IntegerField(choices=[[0, 'Reservado'], [1, 'Completado'], [2, 'Anulado'], [3, 'No Asisten']])),
                ('observacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Seminario',
        ),
    ]
